### PR TITLE
fix: backticks placement issue with `use-github-autolink` disabled

### LINKED ISSUE #220: bug: links are wrapped in code blocks
## Usage
I use the action to generate changelog for releases made to GitHub and other platforms like [Modrinth](https://modrinth.com/) (which also supports markdown changelogs). Obviously, GitHub auto-linking won't work off-site and thus I have it disabled.

## Current Behavior
When setting `use-github-autolink` to `false` all generated links are wrapped in \`\` codeblock ticks, causing said links to be unusable as they entire line is read as code.

See this in action here: <https://github.com/milkdrinkers/Enderchester/releases/tag/2.3.1-RC.4>.

## Expected Behavior
I assume the expected behavior is for the Markdown links to be inserted in the changelog without the \`\` codeblock ticks. This would result in the Markdown links `[]()` becoming parsed resulting in a readable and functional changelog output.

## Reproduction
```yaml
      # Generate changelog
      - name: Generate Changelog
        uses: ardalanamini/auto-changelog@v4
        id: changelog
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-types: |
            feat: New Features
            fix: Bug Fixes
            build: Build System & Dependencies
            perf: Performance Improvements
            docs: Documentation
            test: Tests
            refactor: Refactors
            chore: Chores
            ci: CI
            style: Code Style
            revert: Reverts
          default-commit-type: Other Changes
          release-name: ${{ github.ref_name }}
          mention-authors: true
          mention-new-contributors: true
          include-compare-link: true
          include-pr-links: true
          include-commit-links: true
          semver: true
          use-github-autolink: false
```

https://github.com/milkdrinkers/Enderchester/blob/2bcc81d56643ef08a2e83538f09cd96c0af31104/.github/workflows/deploy.yml#L71

### PR DESCRIPTION
**Pull request by darksaid98**
Fixes an issue where some links would be quoted in backticks causing them to be rendered as code instead of markdown links.

Closes #220.

### CODE REVIEW

File: src/footer.ts [hunk 1]
```diff
@@ -70,7 +70,7 @@ export async function generateFooter(previousTagName?: string): Promise<string>
   if (includeCompareLink() && previousTagName) {
     let link = `${ url }/compare/${ previousTagName }...${ tagName }`;
 
-    if (!useGitHubAutolink() || releaseNamePrefix()) link = `\`[${ previousTagName }...${ tagName }](${ url }/compare/${ previousTagName }...${ tagName })\``;
+    if (!useGitHubAutolink() || releaseNamePrefix()) link = `[${ previousTagName }...${ tagName }](${ url }/compare/${ previousTagName }...${ tagName })`;
```
Comment (ardalanamini) [inline src/footer.ts:73]:
```suggestion
    if (!useGitHubAutolink() || releaseNamePrefix()) link = `[\`${ previousTagName }...${ tagName }\`](${ url }/compare/${ previousTagName }...${ tagName })`;
```

File: src/nodes/commit-hash.ts [hunk 2]
```diff
@@ -59,7 +59,7 @@ export class CommitHashNode extends Node {
     if (shouldUseGithubAutolink) return sha;
 
     // eslint-disable-next-line @typescript-eslint/no-magic-numbers
-    return `\`[${ sha.slice(0, 7) }](${ repo.url }/commit/${ sha })\``;
+    return `[${ sha.slice(0, 7) }](${ repo.url }/commit/${ sha })`;
```
Comment (ardalanamini) [inline src/nodes/commit-hash.ts:62]:
```suggestion
    return `[\`${ sha.slice(0, 7) }\`](${ repo.url }/commit/${ sha })`;
```

File: tests/footer.test.ts [hunk 3]
```diff
@@ -138,7 +138,7 @@ it("should generate the changelog footer with the full changelog link", async ()
 
   const result = await generateFooter(info.previous.name);
 
-  expect(result).toEqual(`\n\n**Full Changelog**: \`[${ info.previous.name }...${ releaseNameInputValue }](${ url }/compare/${ info.previous.name }...${ releaseNameInputValue })\``);
+  expect(result).toEqual(`\n\n**Full Changelog**: [${ info.previous.name }...${ releaseNameInputValue }](${ url }/compare/${ info.previous.name }...${ releaseNameInputValue })`);
```
Comment (ardalanamini) [inline tests/footer.test.ts:141]:
```suggestion
  expect(result).toEqual(`\n\n**Full Changelog**: [\`${ info.previous.name }...${ releaseNameInputValue }\`](${ url }/compare/${ info.previous.name }...${ releaseNameInputValue })`);
```

File: tests/nodes/commit-hash.test.ts [hunk 4]
```diff
@@ -84,5 +84,5 @@ it("should print the sha with the link (not using autolink)", () => {
   expect(commitHashNode.shouldUseGithubAutolink).toBe(false);
 
   // eslint-disable-next-line @typescript-eslint/no-magic-numbers
-  expect(commitHashNode.print()).toBe(`\`[${ sha.slice(0, 7) }](${ context.serverUrl }/${ repo.owner }/${ repo.repo }/commit/${ sha })\``);
+  expect(commitHashNode.print()).toBe(`[${ sha.slice(0, 7) }](${ context.serverUrl }/${ repo.owner }/${ repo.repo }/commit/${ sha })`);
```
Comment (ardalanamini) [inline tests/nodes/commit-hash.test.ts:87]:
```suggestion
  expect(commitHashNode.print()).toBe(`[\`${ sha.slice(0, 7) }\`](${ context.serverUrl }/${ repo.owner }/${ repo.repo }/commit/${ sha })`);
```

**Review by ardalanamini — CHANGES_REQUESTED** [review]
I've requested some changes to the fix, according to the goal I wanted to achieve by using the backticks in the first place, which was to look similar to when the auto link option is enabled, but I've placed them wrongly as you've pointed out.

Thanks for reporting the issue & opening this PR to fix it 👍🏻

**Comment by darksaid98** [comment]
> I've requested some changes to the fix, according to the goal I wanted to achieve by using the backticks in the first place, which was to look similar to when the auto link option is enabled, but I've placed them wrongly as you've pointed out.
> 
> Thanks for reporting the issue & opening this PR to fix it 👍🏻

Fair enough, should be good now!
